spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  profiles:
    active: native
  security:
    user2:
      password: admin
server:
  port: 8888

